image: openjdk:11-jdk

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

# Use `gradlew check --continue` locally to run all tests defined in build.gradle
junit:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - 'build/reports/'

checkstyle:app:
  stage: test
  script:
    - ./gradlew checkstyleMain
  artifacts:
    paths:
      - 'build/reports/'

checkstyle:tests:
  stage: test
  script:
    - ./gradlew checkstyleTest
  artifacts:
    paths:
      - 'build/reports/'

spotbugs:app:
  stage: test
  script:
    - ./gradlew spotbugsMain
  artifacts:
    paths:
      - 'build/reports/'

spotbugs:tests:
  stage: test
  script:
    - ./gradlew spotbugsTest
  artifacts:
    paths:
      - 'build/reports/'


# TODO: (for students) Add JaCoCo test-report generation with artifact, JavaDoc-HTML generation